DROP SCHEMA IF EXISTS tpdb CASCADE;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE SCHEMA tpdb;

DROP TABLE IF EXISTS tpdb."User";

CREATE UNLOGGED TABLE tpdb."User"
(
    id SERIAL PRIMARY KEY,
    nickname CITEXT UNIQUE NOT NULL,
    fullname TEXT NOT NULL,
    about TEXT,
    email CITEXT UNIQUE NOT NULL
);

SELECT * FROM tpdb."User"
